import { ThemeProvider} from './ThemeContext';
import { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import Footer from '../components/Footer';
import Header from '../components/Header';
import Container from '../components/Container';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Musico',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <ThemeProvider>
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <Header />
          <Container>
            {children}
          </Container>
          <Footer />
        </body>
      </html>
  </ThemeProvider>
  );
}
